---
name: iOS Build and Test
on:
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer
      - name: Show current version of Xcode
        run: xcodebuild -version
      - name: Build and Test
        uses: sersoft-gmbh/xcodebuild-action@v3.2.0
        with:
          project: EPCollaboratif.xcodeproj
          scheme: EPCollaboratif
          destination: platform=iOS Simulator,name=iPhone 15
          action: test
          build-settings: CODE_SIGNING_ALLOWED='NO'
          result-bundle-path: TestResults/TestResults.xcresult
      - name: Process Test Results
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults/TestResults.xcresult
        if: success() || failure()
